name: Build WinWheel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile WinWheel executable
      run: |
        # 编译为原生的 Windows GUI 程序以隐藏控制台黑框 (-SUBSYSTEM:WINDOWS)
        # O2作全局优化，MD连接动态C运行库，减小体积
        cl.exe /nologo /O2 /MD /Fe:winwheel.exe winwheel.c /link /SUBSYSTEM:WINDOWS

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: winwheel-exe
        path: winwheel.exe
